name: Run Tests on Push

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # You can change this version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add other dependencies here if needed
          pip install -r requirements.txt

      - name: Run test file
        run: |
          pytest
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
